### ISSUE TITLE
implement editable user profile

### ISSUE THREAD

**Issue by arikgrahl** [die-offene-gesellschaft/platform#11]
- [x] wie participate, nur roter Container (vorausgefüllt)
- [x] keine toc checkbox; stattdessen "Profil löschen" Button
- [x] Bild Vorschau
- [x] Bild löschen
- [x] Passwort ändern
- [x] sinnvolle, ruhige Anordnung aller Inputs
- [x] Einleitung, Hints & Placholder Texte
- [x] update `locked` Attribut

**Comment by nomad5000** [comment]
Der Image upload button sollte so sein wie auf der Mitmachen seite.

**Comment by arikgrahl** [comment]
@nomad5000: already covered by #25.
