### ISSUE TITLE
participate - password validation

### ISSUE THREAD

**Issue by LucidBerlin** [die-offene-gesellschaft/platform#26]
there is no password length validation at the moment

**Comment by RGreinacher** [comment]
Der Fehler lag viel mehr im Label das angab das Passwort müsse 8 Zeichen lang sein. Validiert wurde bisher aber nur eine Mindestlänge von 6 Zeichen.
Durch den Fix wird nun ein Passwort von 8 Zeichen Länge erzwungen, wie auch durch das Label suggeriert.
