### ISSUE TITLE
user profile – edit mask

### ISSUE THREAD

**Issue by LucidBerlin** [die-offene-gesellschaft/platform#29]
- [ ] no video embed on user profil edit page (only for admins)
- [ ] change position of field 'password'

![bildschirmfoto 2016-10-17 um 13 16 24](https://cloud.githubusercontent.com/assets/22854235/19439063/05abd818-947d-11e6-87c2-a304f31c85b1.png)

**Comment by RGreinacher** [comment]
Videos nur für Admins war mir nicht klar, wird gemacht!

Das PW Feld habe ich bewusst nach rechts unten gesetzt, weil es immer zum Abschluss der Änderungen als Bestätigung benötigt wird. Thematisch passt es natürlich gut zu den anderen Passwörtern nach links, aber durch den Fluss durch das Interface habe ich es mir rechts unten vorgestellt. Dennoch ändern?

**Comment by LucidBerlin** [comment]
> Videos nur für Admins war mir nicht klar, wird gemacht!

sorry. das hab ich vielleicht nicht richtig kommuniziert.. 

> Das PW Feld habe ich bewusst nach rechts unten gesetzt, weil es immer zum Abschluss der  Änderungen als Bestätigung benötigt wird. Thematisch passt es natürlich gut zu den anderen Passwörtern nach links, aber durch den Fluss durch das Interface habe ich es mir rechts unten vorgestellt. Dennoch ändern?

Für mich sieht es wie etwas aus, das ich ausfüllen muss. weil man es aber nicht bearbeiten kann, ist es logischer unter der Email, denke ich.
