### ISSUE TITLE
add all available font weights to project

### ISSUE THREAD

**Issue by nomad5000** [die-offene-gesellschaft/platform#32]
check how to add Montserat Font in diferent weights 

Slim Bold Regular ...

**Comment by arikgrahl** [comment]
Just add a web font which supports those weights.
Montserrat served by google fonts currently supports

```
regular 400
bold 700
```

Make sure it is legal to include a new font file to the repo or serve it from a CDN.

**Comment by nomad5000** [comment]
Since we found a source where there are other weights available


It would be nice to use these fonts on the site

**Comment by nomad5000** [comment]
checked if legal:

https://github.com/google/fonts/tree/master/ofl/montserrat

**Comment by arikgrahl** [comment]
seems ok (but I am no lawyer and give no legal advices).

Use this list to map the ttf fonts to numeric font-weights:

- 100 - Thin
- 200 - Extra Light (Ultra Light)
- 300 - Light
- 400 - Normal
- 500 - Medium
- 600 - Semi Bold (Demi Bold)
- 700 - Bold
- 800 - Extra Bold (Ultra Bold)
- 900 - Black (Heavy)

CSS code code look like the following:

```
@font-face {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 400;
  src: url('<%= asset_path('fonts/montserrat-regular.ttf') %>');
}

/* ... */
```

**Comment by nomad5000** [comment]
In the sccs files it is not possible to use 
url('<%= asset_path('fonts/montserrat-regular.ttf') %>');
When I do so I get a 500 error for the request with this call
`/assets/<%= asset_path('fonts/montserrat-regular.ttf') %>`
So the <%= tags are rendered

So I tried this approach:
[importatn line](https://github.com/die-offene-gesellschaft/platform/blob/32-add-all-available-font-weights-to-project/app/assets/stylesheets/application.scss#L14)
Now I get a 400 error for the corresponding request

`http://localhost:3000/fonts/400-montserat-normal.ttf`

so I tried the following making the request by hand:

`http://localhost:3000/assets/400-montserat-normal.ttf` -> 400

`http://localhost:3000/assets/fonts/400-montserat-normal.ttf` -> 400

**Comment by RGreinacher** [comment]
Zitat aus Slack:

Du kannst eine fonts.scss**.erb** Datei anlegen und darin etwa so etwas anstellen:

@font-face {
 font-family:  '*Font-Name-der-als-Font-Family-verwendet-werden-soll*';
 src: url('<%= asset_path('dateiname-ohne-ordner.ttf') %>');
}

**Comment by RGreinacher** [comment]
Wir sprechen uns gerade ab und schlagen vor, dass wir das Anlegen übernehmen, zB exemplarisch an einem Beispiel.

**Comment by nomad5000** [comment]
Finde ich großartig

**Comment by nomad5000** [comment]
Am besten ihr nutzt dazu den FB den ich angelegt habe
