### ISSUE TITLE
implement event registration form

### ISSUE THREAD

**Issue by arikgrahl** [die-offene-gesellschaft/platform#4]
Veranstaltung anmelden

Wir freuen uns, dass Sie im Rahmen unserer Initiative eine Veranstaltung anmelden wollen. Gerne nehmen wir Ihre Veranstaltung nach einer Prüfung in unseren Aktionskalender auf und machen sie bekannt. Dafür benötigen wir von Ihnen:

Titel der Veranstaltung:

Thema und Format::
[z.B.: Debatte über xy, Lesung von xy, …]

Veranstalter: [z.B.: Studentengruppe, Verein, Stiftung, Theater…]

Mitwirkende (optional):

Termin/Uhrzeit:

Veranstaltungsort (Adresse):

Ansprechpartner
Vorname:
Nachname:
Mailadresse:
Telefon:

Logo Ihrer Organisation (optional): [Hochladen]

Foto/Bild zur Ankündigung (optional): [Hochladen]

Inwiefern setzt Ihre Veranstaltung ein Zeichen für eine offenen Gesellschaft?
[z.B.: “Es begegnen sich Menschen unterschiedlichen Glaubens...”]

[x] Ich erkläre mich damit einverstanden:

bei der Einladung zur Veranstaltung das Logo der Initiative zu nutzen (Digital, Print).
vor Ort das Material (Postkarten/Flyer...) zu verwenden, das mir die Initiative zur Verfügung stellt
der Initiative bei der Dokumentation meiner Veranstaltung zu helfen und hierzu die erforderlichen Rechte an mindestens einem Foto einzuräumen (Bitte weisen Sie die Besucher darauf hin, wenn fotografiert und/oder aufgezeichnet wird).

[Anmeldung abschicken]

Sie haben Fragen? Hier finden Sie unseren Leitfaden für Aktionspartner

-----------------------------------

Antwort-Fenster (oder Antwort-Mail) nach Absenden

Danke! Wir prüfen Ihre Anmeldung und melden uns möglichst bald bei Ihnen zurück.

Ihr Team der Initiative Offene Gesellschaft

**Comment by RGreinacher** [comment]
This fits perfectly to my issue #5
