### ISSUE TITLE
implement idea registration form

### ISSUE THREAD

**Issue by arikgrahl** [die-offene-gesellschaft/platform#5]
Idee mitteilen

Schildern Sie uns Ihre Aktionsidee im Sinne einer offenen Gesellschaft. Wir geben Ihnen möglichst bald Feedback...

Titel der Aktion:

Worum geht es?
[z.B.: Diskussion, Picknick, Bootsfahrt, Lesung mit xy....]

Wie setzt Ihre Aktion ein Zeichen für eine offenen Gesellschaft?
[z.B.: “Es begegnen sich Menschen unterschiedlicher Herkunft...”]

Wunschtermin:

Wunschort:

Mitwirkende (optional):

Ansprechpartner
Vorname:
Nachname:
Mailadresse:
Telefon:

[Button: Senden]

-----------------------------

Antwort-Fenster (oder Antwort-Mail) nach Absenden

Danke für Ihre Idee! Wir melden uns möglichst bald bei Ihnen zurück.

Ihr Team der Initiative Offene Gesellschaft

**Comment by RGreinacher** [comment]
done; adding #4 to feature branch
