### ISSUE TITLE
add end date for events which last several days

### ISSUE THREAD

**Issue by arikgrahl** [die-offene-gesellschaft/platform#63]

**Comment by LucidBerlin** [comment]
just add the end-date with a dash. 

**desktop**
<img width="1187" alt="bildschirmfoto 2016-10-31 um 19 10 04" src="https://cloud.githubusercontent.com/assets/22854235/19865774/df283ec6-9f9d-11e6-9254-6ca718fab9a0.png">

**mobil**
<img width="598" alt="bildschirmfoto 2016-10-31 um 19 10 13" src="https://cloud.githubusercontent.com/assets/22854235/19865782/e59000d2-9f9d-11e6-9d54-d5db8fec5a5f.png">
